# permissions for end users to view randomstrings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randomstring-viewer-role
rules:
- apiGroups:
  - encryption.jobilla.dev
  resources:
  - randomstrings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - encryption.jobilla.dev
  resources:
  - randomstrings/status
  verbs:
  - get
